apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo-01
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-echo
  template:
    metadata:
      labels:
        app: grpc-echo
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/public/grpc-echo:0.0.3
          imagePullPolicy: Always
          name: grpc-echo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "v0.0.3"
            - name: KIND
              value: "grpc-echo-01"
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8080
            initialDelaySeconds: 2
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo-02
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-echo
  template:
    metadata:
      labels:
        app: grpc-echo
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/public/grpc-echo:0.0.3
          imagePullPolicy: Always
          name: grpc-echo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: VERSION
              value: "v0.0.3"
            - name: KIND
              value: "grpc-echo-02"
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8080
            initialDelaySeconds: 2
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-02
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo
  namespace: test
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8080
      protocol: TCP
  selector:
    app: grpc-echo